language: php
php:
    - 7.4

before_script: 
    - composer install
    - if [[ $TRAVIS_PHP_VERSION = "7.0" ]]; then echo yes | pecl install apcu 5.1.5; fi
    - if [[ $TRAVIS_PHP_VERSION = "7.1" ]]; then echo yes | pecl install apcu 5.1.6; fi
    - echo $'apc.enabled=1\napc.enable_cli=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success: 
    - bash <(curl -s https://codecov.io/bash)