language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3

before_script: 
    - composer install
    - pecl install apcu_bc   

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success: 
    - bash <(curl -s https://codecov.io/bash)